### ISSUE TITLE
Presentase my skill

### ISSUE THREAD

**Issue by superpikar** [Fakhri17/Web-Profil#1]
![image](https://user-images.githubusercontent.com/2832280/65226746-9c8d7300-daf1-11e9-8682-427dc13cad7b.png)

- tampilkan juga presentasenya berapa % sehingga pembaca bisa mengetahui nilai dari progress bar

**Comment by Fakhri17** [comment]
Presentase untuk skilll

![image](https://user-images.githubusercontent.com/54692387/65319422-cdd97200-dbc9-11e9-94d7-a66a3a2689e2.png)
