### ISSUE TITLE
Gallery portfolio tidak sesuai requirement

### ISSUE THREAD

**Issue by superpikar** [Fakhri17/Web-Profil#2]
![image](https://user-images.githubusercontent.com/2832280/65226945-fbeb8300-daf1-11e9-88b4-43fcece349a4.png)

- tampilkan nama/judul project di bawah thumbnail project
- tiap project harusnya memiliki galeri foto masing2, tidak menyambung satu sama lain
- sebagai gambaran yg dimaksud, lihat kode dari Rama https://github.com/Arararra/web-personal

**Comment by Fakhri17** [comment]
Perbaikan Portfolio dan Galeri

![image](https://user-images.githubusercontent.com/54692387/65319537-1002b380-dbca-11e9-9fb0-4ae26434531e.png)

Tampilan  galeri web porfolio

![image](https://user-images.githubusercontent.com/54692387/65319600-39234400-dbca-11e9-8252-cfa4350f214d.png)

Tampilan  galeri edit foto

![image](https://user-images.githubusercontent.com/54692387/65319844-c23a7b00-dbca-11e9-9e09-9d3a7ab13eb2.png)


Tampilan galeri web company

![image](https://user-images.githubusercontent.com/54692387/65320183-83f18b80-dbcb-11e9-90c9-5da54a524e57.png)
