### ISSUE TITLE
HTML tidak perlu dimasukkan ke PHP array

### ISSUE THREAD

**Issue by superpikar** [Fakhri17/Web-Profil#3]
![image](https://user-images.githubusercontent.com/2832280/65227630-330e6400-daf3-11e9-8ac0-2b7f24b49a35.png)

cukup 
```
[
  {
     ......
    'persen' => 60
  }
]
```
baru nanti ketika dirender jadi 
```
<progress class="progress is-link" value="<?php echo $value['persen'] ?>" max="100"></progress>
```

Begitu juga untuk $pendidikan, cukup string dari image url yang disimpan dalam PHP array

![image](https://user-images.githubusercontent.com/2832280/65227938-bfb92200-daf3-11e9-8ce5-062df32826f2.png)

**Comment by Fakhri17** [comment]
Perbaikan PHP Array

![image](https://user-images.githubusercontent.com/54692387/65318939-cebdd400-dbc8-11e9-869b-f84b1d746789.png)

![image](https://user-images.githubusercontent.com/54692387/65318986-e2693a80-dbc8-11e9-94b7-e6292cdc6587.png)
